name: Docker Container CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build the Docker Image from our Dockerfile
      - name: Build Docker Image
        run: docker build -t calculator-app:latest .

      # Run the container. It will automatically execute the CMD from the Dockerfile
      - name: Run Tests in Container
        run: docker run calculator-app:latest
